env:
    jasmine: true
    node: true
    mocha: true
rules:
    const: 0
    indent:
        - 2
        - 4
        - SwitchCase: 1
    object-curly-spacing: 0
    semi: 2
    prefer-const:
        - 1
extends: airbnb/base
parserOptions:
    ecmaVersion: 6
    sourceType: module
